### ISSUE TITLE
Show errors on textfield after api call

### ISSUE THREAD

**Issue by jordandevogelaere** [joanpablo/reactive_forms#226] opened 2021-10-20 12:27 UTC
Hi all, 

I've question according to show errors to specific fields.

Is it possible to add errors to fields in a reactive form after an api call that returns an error.

ex.

```
 FormGroup formGroup = FormGroup({
    'user_name': FormControl<String>(),
    'firstname': FormControl<String>(),
    'lastname': FormControl<String>(),
    'email': FormControl<String>(validators: [
      Validators.email,
    ]),
  });
```

Button at the bottom of the screen that creates an account. 

So on button click all fields are valid;

How to show an error on the username input field when the api returns an error. 
f.e "Username already exists" ?

Thanks in advance

**Comment by joanpablo** [comment] 2021-10-29 20:42
Hi @jordandevogelaere,

You can have two approaches:

1- The one described by @vasilich6107 above
2- Create a custom Async Validator to the Username/Email

inside the folder **example** of the project, there is an implementation of the approach.


```dart
FormGroup form = fb.group(<String, Object>{
   'email': FormControl<String>(
      validators: [Validators.required, Validators.email],
      asyncValidators: [_uniqueEmail]
   )
});
```

```dart
Future<Map<String, dynamic>?> _uniqueEmail(AbstractControl<dynamic> control) async {
  final error = {'unique': false};

  final emailAlreadyInUse = await Future.delayed(
    const Duration(seconds: 5), // delay to simulate a time consuming operation
    () => inUseEmails.contains(control.value.toString()),
  );

  if (emailAlreadyInUse) {
    control.markAsTouched();
    return error;
  }

  return null;
}
```

**Comment by joanpablo** [comment] 2021-11-21 14:03
Hi @jordandevogelaere,

Have you solved your issue? Any update on it would be very greatful.

**Comment by jordandevogelaere** [comment] 2021-11-25 09:27
Hi @joanpablo ,

Thanks for your answer. 

It was solved by the approach @vasilich6107 described.

Thank you both!

**Comment by vasilich6107** [comment] 2021-11-25 10:30
Hi @jordandevogelaere 
If the issue is solved - do not forget to close the issue.

**Closed** 2021-11-25 10:54 UTC
