### ISSUE TITLE
Type problems

### ISSUE THREAD

**Issue by kuhnroyal** [joanpablo/reactive_forms#102] opened 2021-03-03 14:56 UTC
The 9.x version broke a couple of things related to types.

The main thing that is not working for me anymore are validators:

```dart
FormControl<int>(
  validators: [
    (control) {
      // type error
      // type '(AbstractControl<int>) => Map<String, dynamic>' is not a subtype of type '(AbstractControl<dynamic>) => Map<String, dynamic>'
    }
  ],
),
```

This happens due to missing generic types here: https://github.com/joanpablo/reactive_forms/blob/master/lib/src/models/models.dart#L89

But if I add the types there, then the form builder (which I don't use) doesn't work anymore as it completely relies on `dynamic` and is not type safe at all.

```
00:02 +136 -1: /Users/foo/workspace/flutter/reactive_forms/test/src/models/form_builder_test.dart: Form Builder Build a group with multiple validators [E]                                      
  type 'List<(AbstractControl<String>) => Map<String, dynamic>>' is not a subtype of type 'List<(AbstractControl<dynamic>) => Map<String, dynamic>>'
  test/src/models/form_builder_test.dart 163:38  main.<fn>.<fn>
  
00:02 +136 -2: /Users/foo/workspace/flutter/reactive_forms/test/src/models/form_builder_test.dart: Form Builder Build a group with default value and validator [E]                              
  type 'List<(AbstractControl<String>) => Map<String, dynamic>>' is not a subtype of type 'List<(AbstractControl<dynamic>) => Map<String, dynamic>>'
  test/src/models/form_builder_test.dart 183:38  main.<fn>.<fn>
```

The whole form builder will never work with strong typing in its current design.
I suggest to create a new form builder with strong typing by using Dart chaining, something like this:

```dart
fb
  ..control<String>('foo', value: 'bar', validators: [...], ...)
  ..control<int>('int', ...)
  ..group('my-group', (g) => g
        ..control<X>('x', ...)
        ..control<Y>('y', ...))
  ..array('my-array', (a) => a
        ..control<Z>('z', ...))
``` 

FYI @vasilich6107

**Comment by joanpablo** [comment] 2021-03-03 22:22
Hi @kuhnroyal,

Thanks for the issue, very useful. I have detected a problem that for some reason didn't come up in tests (a bug is always a missing test). I had to roll back the strong type in ValidatorFunctions.

Please update and try the last version 9.0.2, and let me know if the issue is solved.

Thanks and Best regards

**Comment by kuhnroyal** [comment] 2021-03-05 12:24
`9.0.2` works but it is also a step backwards. `dynamic` is the mortal enemy of null-safety. I strongly suggest to get rid of the dynamic form builder and add strong typing before adding null-safety. Otherwise null-safety will in most cases not have the desired impact.

**Comment by joanpablo** [comment] 2021-03-05 13:29
You are right @kuhnroyal, after finish the opened issues related to some bugs, I will focus on null-safety. Your issue helps me to detect a unit test that was not correctly coded. I'm glad that everything is now working as expected for you. For now, I will close the issue. Please don't hesitate to open it again or to open another if you find any other issue.

Best regards

**Closed by joanpablo** 2021-03-05 13:29 UTC
