### ISSUE TITLE
ReactiveDropdownField not showing Text with Release Web Build

### ISSUE THREAD

**Issue by sbosell** [joanpablo/reactive_forms#39] opened 2020-10-06 21:36 UTC
Having a ReactiveDropDownField like the following the release web build doesn't display the Text in the dropdown. Additionally the label is cut off on the element.

```
 ReactiveDropdownField<int>(
                    formControlName: 'locationSpotId',
                    //hint: Text('Spot Number'),
                    decoration: InputDecoration(
                        border: OutlineInputBorder(),
                        //contentPadding: EdgeInsets.fromLTRB(0, 5.5, 0, 0),
                        labelStyle: TextStyle(),
                        labelText: 'Parking Spot #'),
                    items: widget.data.location.locationSpots
                        .map((x) => DropdownMenuItem(child: Text(x.name), value: x.id))
                        .toList()),
```

Here is a screencast showing both. The first part of the video shows the form built in release mode and the 2nd hafl of the video in profile mode.

https://www.dropbox.com/s/npubiunoto34pgq/2020-10-06_16-31-57.MP4?dl=0

**Comment by joanpablo** [comment] 2020-10-06 22:39
Hi @sbosell,

Thanks for using Reactive Forms and for the issue. Could you please show me the FormGroup definition and also how do you load **widget.data.location.locationSpots** items?

**Comment by sbosell** [comment] 2020-10-06 22:47
No problem.  Awesome package by the way.

There is a future builder above the form, when it resolves it passes the data to the widget so it receives a list which in this case you can consider has an id and name (locationSpot).  The actual form widget is receiving the data in the constructor.

final form = FormGroup({
  'lastName': FormControl(validators: []),
  'phoneNumber': FormControl(validators: [Validators.required, Validators.pattern(phoneValidationPattern)]),
  'locationSpotId': FormControl(validators: [Validators.required]),
});

class WebApi {
  final Reader read;
  WebApi(this.read);

  Future<FormDataRequestResponse> getFormData(int clientId, int locationId) {
    return read(clientResolverProvider).get(FormDataRequest(clientId: clientId, locationId: locationId));
  }
}

final webApiProvider = Provider((ref) => WebApi(ref.read));

 Widget curbsideForm() {
    return Consumer(builder: (context, watch, child) {
      return FutureBuilder<FormDataRequestResponse>(
          future: WebApi(context.read).getFormData(clientId, locationId),
          builder: (BuildContext context, AsyncSnapshot<FormDataRequestResponse> data) {
            if (!data.hasData) return CircularProgressIndicator();
            return curbsideFormColumns(context, data.data, clientId, locationId);
          });
    });
  }
}

**Comment by joanpablo** [comment] 2020-10-06 22:58
@sbosell I have test your code in Flutter Mobile (not web) and it works fine.
Right now I don't have installed flutter channel beta for testing the code in the Flutter Web, I will install it latter at night. but mean while help me to make some tests. Could you please change the ReactiveDropdown with a native regular **DropdownButtonFormField** to see if the **labelText** is also truncated, and if items are correctly loaded?

**Comment by sbosell** [comment] 2020-10-06 23:06
@joanpablo  Flutter Mobile is fine, I rarely see problems there but the web is another story.  I tested this on flutter web beta and dev in profile and release modes.  The video was taken from the dev branch but if I recall the beta has the same issue.  I'll test and see what happens with the DropdownButtonFormField.

**Comment by sbosell** [comment] 2020-10-06 23:58
@joanpablo  

Profile mode:
First drop down is the DropdownButtonFormField and 2nd is the reactive one. 
 

Video: https://www.dropbox.com/s/p6463pe6hy877do/2020-10-06_18-53-20.MP4?dl=0

Release mode:

Text not displaying in either.

Video: https://www.dropbox.com/s/lxkuk28f6uimd2r/2020-10-06_18-57-40.MP4?dl=0

**Comment by joanpablo** [comment] 2020-10-07 00:15
Hi @sbosell,

Thanks a lot for testing it. ReactiveDropdownField is implemented almost exactly as DropdownButtonFormField; it's almost a wrapper. So it seems to be a problem in the native Flutter DropdownButtonFormField implementation??? Do you have some Theme implemented that maybe is adding some padding to the Floating Label?

In release mode, are you sure **x.name** gets a value??? Have you tried the old school way of put a **print(x.name)**?? :)

**Comment by joanpablo** [comment] 2020-10-07 00:36
@sbosell I'm not sure if Dartpad.dev engine uses the same engine that Flutter Web.
I have paste a big part of Reactive Form's code in Dartpad.dev and test de ReactiveDropdownField and it seams to work great.

Here is the sample:
https://dartpad.dev/743187ba3ca50ee3396881f6aa413292

let me know if you can see it.

**Comment by joanpablo** [comment] 2020-10-09 00:28
Hi @sbosell,

I've test Reactive Forms and dropdown with 

```shell
[√] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
```

And is working OK. Not truncated label and data is loaded.

Here is the code I have tested:

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';

/// Simple location spot class
class LocationSpot {
  final String name;
  final int id;

  LocationSpot(this.name, this.id);
}


/// Simple demo UI view
class ReactiveDropDownButtonTest extends StatefulWidget {
  @override
  _ReactiveDropDownButtonTestState createState() =>
      _ReactiveDropDownButtonTestState();
}

class _ReactiveDropDownButtonTestState
    extends State<ReactiveDropDownButtonTest> {

  /// For using in StreamBuidler instead of a FutureBuilder
  final controller = StreamController<List<LocationSpot>>();

  @override
  void dispose() {
    controller.close();
    super.dispose();
  }

  /// The FormGroup definition, I've remove other fields for simplicity
  final form = FormGroup({
    'locationSpotId': FormControl(validators: [Validators.required]),
  });

  /// Rebuild the ReactiveForm after received data (not recomended, try always to rebuild only the ReactiveDropdownField)
  Widget _buildForm(BuildContext context, List<LocationSpot> spots) {
    return ReactiveForm(
      formGroup: this.form,
      child: Column(
        children: [
          ReactiveDropdownField<int>(
              formControlName: 'locationSpotId',
              decoration: InputDecoration(
                border: OutlineInputBorder(),
                labelStyle: TextStyle(),
                labelText: 'Parking Spot #',
              ),
              items: spots
                  .map(
                      (x) => DropdownMenuItem(child: Text(x.name), value: x.id))
                  .toList()),
        ],
      ),
    );
  }

  /// Load data from web api and notify UI with a stream
  void _loadData() {
    this.controller.add([
      LocationSpot('100', 1),
      LocationSpot('200', 2),
    ]);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            RaisedButton(
              child: Text('Load Data'),
              onPressed: _loadData,
            ),
            StreamBuilder<List<LocationSpot>>(
              stream: controller.stream,
              builder: (context, snapshot) {
                if (!snapshot.hasData) {
                  return CircularProgressIndicator();
                }

                return _buildForm(context, snapshot.data);
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

You can see the GIF here

[Sample](https://www.dropbox.com/s/wnffhlw19z4pxm2/chrome-capture.gif?dl=0)

I've created the sample trying to deduce your logic. There are some suggestions I would like to give you: 

First don't put when possible a **ReactiveForm** widget under a StreamBuilder o FutureBuilder (opposit as I did in the above example). A **ReactiveForm** never change so in this case is better to only wrap the **ReactiveDropdownField** with the StreamBuilder or FutureBuilder not the whole ReactiveForm.

Second try always to specify a data type in your controls or use a **FormBuilder** for example:

```dart
final form = fb.group({
  'lastName': '',
  'phoneNumber': ['', Validators.required, Validators.pattern(phoneValidationPattern)],
  'locationSpotId': FormControl<int>(validators: [Validators.required]),
});
```



Could you please show me your code so we can determine what the issue is?

**Comment by sbosell** [comment] 2020-10-09 01:48
@joanpablo  The issue was not in debug/emulator but when you build it in release or profile mode.   I'm going to try to put together a stand alone sample this weekend with profile, release and debug modes at a shareable site.

**Comment by joanpablo** [comment] 2020-10-09 16:18
Hi @sbosell,

I've tested the same above code with **profile** and **debug** modes and all works fine. These where the commands a used:

```shell
flutter run -d edge --profile
```

```shell
flutter run -d edge --release
```

I also build **release** and **profile** and deploy on local http server:

```shell
flutter build web --profile
```

```shell
flutter build web --release
```

And then start a local server with **Nodejs** 

```shell
npm install --global http-server
```

navigate to */build/web/* folder

```shell
http-server .
```

Please try the above code and let me know if your issue persists or not. 
In case the issue is not present in the above code then show me more of your code to try to reproduce in my environment.

Thanks.

**Comment by sbosell** [comment] 2020-10-10 22:30
@joanpablo I was able to reproduce the label issue.  If I add a network sourced image above the form the label on the dropdown is truncated.  Remove the image and the label works correctly.  I'm going to publish the stand alone samples tomorrow.

Still working on reproducing the other issue which is more problematic.

**Comment by joanpablo** [comment] 2020-10-10 22:48
Thanks for the answer @sbosell. When you have implemented the sample, please share the code here to reproduce the issue in my environment.

**Comment by sbosell** [comment] 2020-10-11 00:57
@joanpablo-
Here are the tests (Checked in chrome and edge):

**Label Cut off:**
https://pmgtemp.blob.core.windows.net/flutter-test/profile-image/index.html#/
https://pmgtemp.blob.core.windows.net/flutter-test/release-image/index.html#/

![image](https://user-images.githubusercontent.com/1896962/95667927-67a3f200-0b32-11eb-9151-2ba7fd1d3e64.png)

**Label Ok:**
https://pmgtemp.blob.core.windows.net/flutter-test/profile-no-image/index.html#/
https://pmgtemp.blob.core.windows.net/flutter-test/release-no-image/index.html#/

![image](https://user-images.githubusercontent.com/1896962/95667940-8609ed80-0b32-11eb-92a3-03c34cccb347.png)

**Source code:** 

https://github.com/sbosell/flutter-reactive-form-testing

I tried to set this up as close to what I have in my app as possible.  I did not make any changes per your recommendations yet as I wanted to reproduce the issues.  The only difference between the image/no-image releases above is a bool being set to hide the image as indicated in the comments in the code.  I tested it with a button to show/hide the image but it didn't reproduce the issue.

I'm going to see if I can get the empty Drop down text to reproduce but as of yet haven't been able to.

**Comment by joanpablo** [comment] 2020-10-11 01:11
Hi @sbosell,

I've just test your links and everything is fine, even the ones with the image at the top. I'll share a screen shoot of my Desktop.

**Comment by joanpablo** [comment] 2020-10-11 01:21
Hi @sbosell,

In [this link](https://www.dropbox.com/s/yxrrxoth7mb2lyr/Untitled.png?dl=0) I share to you a screenshot with Edge, Opera, and  Chrome, with the links in **release** mode. But I tested all links and all of them are working just fine.

I also changed  **zoom** in the browser to see if it could be the problem but nothing, all works fine for me.

**Comment by joanpablo** [comment] 2020-10-14 16:11
Hi @sbosell,

I have cloned your [repo](https://github.com/sbosell/flutter-reactive-form-testing) and tested the code. I built the flutter web in **profile** mode, and the app run without the issues you are reporting.

In this [gif](https://www.dropbox.com/s/kk50a568ju2bzpz/flutter-web.gif?dl=0) I share to you the test in **Microsoft Edge** browser.
 
What version of Flutter and Chrome/Edge are you using? Do you have some extension in your browser that can be interfering with the web app?

**Comment by sbosell** [comment] 2020-10-15 10:55
I'll have some time over the weekend to check. It may well be something on my machine and will test it in private mode. If I can't provide more details I'll close the ticket.

**Comment by joanpablo** [comment] 2020-10-16 14:46
Ok @sbosell, I'll be glad to help you with any troubles you may have, so do not hesitate to write to me if you need it.

**Comment by joanpablo** [comment] 2020-10-30 01:10
Hi @sbosell 

I will close the issue since there are no new comments. Feel free to reopen it or open a new one if you have any other issue.

**Closed by joanpablo** 2020-10-30 01:10 UTC
