### ISSUE TITLE
selectAllOnFocus on ReactiveTextField

### ISSUE THREAD

**Issue by carmas123** [joanpablo/reactive_forms#210] opened 2021-09-07 07:37 UTC
Since it is not possible to access to `TextEditController` of `ReactiveTextField` I think that can be hopeful to add a simple new property: `selectAllOnFocus`

This could be useful for auto-selecting text when receiving focus.

Regards.

**Comment by vasilich6107** [comment] 2021-09-09 14:28
Hi @carmas123 
It seems that this issue is duplicate of #209 

If your issues are the same could you close this one in favour of #209

**Comment by carmas123** [comment] 2021-09-09 14:42
This concerns a direct functionality to "autoSelectAll" on focus is received.

**Comment by vasilich6107** [comment] 2021-12-16 13:52
Hi @carmas123 

I release standalone package for text field with exposed controller
https://pub.dev/packages/reactive_text_field

Check how to access the controller in example
https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_text_field/example/lib/main.dart#L47

Does it looks suitable for your needs?

**Comment by joanpablo** [comment] 2021-12-27 15:36
Hi @carmas123,

We have just released v10.7.0. In this version, you can pass a controller to the ReactiveTextField and use it for selection purposes.

**Closed by joanpablo** 2021-12-27 15:36 UTC
Labels: enhancement
