### ISSUE TITLE
Unable to match formControlNames that include a dot ('.')

### ISSUE THREAD

**Issue by Pitazzo** [joanpablo/reactive_forms#242] opened 2021-11-29 19:08 UTC
I've just noticed that in case the string set as `formControlName` in one or more fields of a form includes the dot character (`.`) the plugin is unable to match the widgets of the form and the fields of the FormGroup object and throws a `FormControlNotFoundException control with name: 'com.example' not found.` error.

**Comment by vasilich6107** [comment] 2021-11-29 20:11
Hi @Pitazzo 
The thing is that reactive_forms is using dot as separator for splitting the field path.
This is by design as far as the dot separator is not very common to use in field names)
The easiest way to fix this issue is not to use dot in your field naming

**Comment by Pitazzo** [comment] 2021-11-29 20:36
Hi @vasilich6107
Thanks for your quick reply. Yeah, I supposed something like that and stopped using strings which contain dots. 

However, realising this was the problem took me a lot of time. Thus, I would suggest including this limitation in the `README`, and more importantly, adding some kind of validation so the errors "sounds" in a more clear way.

**Comment by vasilich6107** [comment] 2021-11-30 03:47
@Pitazzo makes sense

**Comment by vasilich6107** [comment] 2021-12-03 10:43
I did the PR with assertion
I hope @joanpablo would be able to release it soon

**Comment by joanpablo** [comment] 2021-12-03 13:15
Hi @Pitazzo and @vasilich6107 

A new version v10.6.6 has been released with a better error message and a better handler to this situation. 

Thanks to @Pitazzo for the issue and thanks to @vasilich6107 for the quick response and solution.

You are making history ; )

**Closed by joanpablo** 2021-12-03 13:15 UTC
